USE BrickCaveau;

-- ==========================================
-- INSERIMENTO SET TEMA: HARRY POTTER
-- ==========================================
INSERT INTO Set_Lego (Codice_Set, Nome, Anno_Uscita, Anno_Ritiro, N_Pezzi, Descrizione, Prezzo, Tema, Quantita_Magazzino) VALUES
(4701, 'Il Cappello Parlante', 2001, 2002, 48, 'Un vero pezzo di storia LEGO! Il primissimo set dedicato al Cappello Parlante. Include la minifigure classica di Harry Potter e un ingegnoso podio con una ruota girevole per smistare casualmente lo studente in una delle quattro Case di Hogwarts (Grifondoro, Serpeverde, Corvonero o Tassorosso).', 64.99, 'Harry Potter', 5),
(4702, 'La Sfida Finale', 2001, 2002, 60, 'Rivivi il momento clou del primo anno ad Hogwarts con questo storico set! Affronta il Professor Raptor e scopri il suo oscuro segreto rimuovendo il turbante per svelare il volto di Lord Voldemort. Il set include le minifigure di Harry Potter e del Professor Raptor, oltre al mistico Specchio delle Brame dove è nascosta la magica Pietra Filosofale. Un classico imperdibile per ricreare l''emozionante scontro finale.', 54.99, 'Harry Potter', 3),
(4704, 'La Stanza delle Chiavi alate', 2001, 2002, 175, 'Affronta un''altra delle pericolose prove a guardia della Pietra Filosofale! In questo storico set del 2001, Harry e Ron si ritrovano nella magica stanza invasa dallo sciame di chiavi alate. Salta a bordo della scopa volante per aiutare Harry a catturare l''unica chiave argentata in grado di sbloccare la pesante porta del castello. Il set include le minifigure di Harry Potter, Ron Weasley e l''imponente pezzo della Regina Bianca degli scacchi magici, che preannuncia la sfida successiva. Un vero gioiello da collezione.', 58.99, 'Harry Potter', 11),
(4726, 'Allenamento di Quidditch', 2002, 2004, 128, 'Preparati a scendere in campo e a perfezionare le tue abilità di volo con questo iconico set del 2002 dedicato allo sport più amato dai maghi! Unisciti a Harry Potter e Draco Malfoy durante un''intensa sessione di allenamento sotto l''occhio vigile dell''istruttrice Madama Bumb. Il set comprende una piccola postazione rialzata, gli anelli dorati, il baule con l''attrezzatura e un divertente meccanismo a catapulta per lanciare fisicamente la Pluffa o i Bolidi attraverso i cerchi. Riuscirai a far vincere la tua Casa e a catturare il Boccino d''Oro prima del tuo avversario? Include le tre minifigure di Harry, Draco (con le rispettive divise da Quidditch) e Madama Bumb.', 44.99, 'Harry Potter', 2),
(4752, 'La Classe del Professor Lupin', 2004, 2004, 156, 'Un''indimenticabile lezione di Difesa Contro le Arti Oscure! Ritorna al 2004 con questo storico set tratto dal film "Il Prigioniero di Azkaban". Aiuta Neville Paciock ad affrontare le sue paure più profonde sfidando il Molliccio, misteriosamente celato all''interno del grande armadio. Grazie a un ingegnoso meccanismo, il mobiletto si apre per rivelare l''esilarante creatura magica con le sembianze del severo Professor Piton, goffamente abbigliato con gli iconici vestiti e il cappello della nonna di Neville! Scaglia l''incantesimo Riddikulus sotto la saggia guida del Professor Remus Lupin. Il set è ricco di dettagli oscuri e pozioni, e include tre minifigure da collezione: Lupin, Neville e l''esclusivo Piton-Molliccio.', 84.99, 'Harry Potter', 0),
(5378, 'Castello di Hogwarts', 2007, 2007, 943, 'Il quinto anno ad Hogwarts non è mai stato così denso di segreti! Uscito nel 2007 in concomitanza con "L''Ordine della Fenice", questo iconico modello del Castello porta in vita le scene più importanti del quinto capitolo della saga. Esplora la Serra per rinvasare le urlanti Mandragole, eludi la sorveglianza per recuperare gli oggetti confiscati nell''ufficio della severissima Professoressa Dolores Umbridge e scopri la porta celata che conduce alla Stanza delle Necessità. Ricco di stanze segrete e dettagli affascinanti, il set include ben 9 minifigure: Harry, Ron, Hermione, Silente, Piton, Hagrid, Draco Malfoy, un temibile Mangiamorte e la primissima, storica versione LEGO di Dolores Umbridge. Un pezzo immancabile per i veri collezionisti!', 557.99, 'Harry Potter', 4),
(75955, 'Espresso per Hogwarts', 2018, 2022, 801, 'Tutti a bordo dell''Espresso per Hogwarts! Attraversa il magico muro di mattoni della stazione di King''s Cross per raggiungere l''iconico Binario 9 ¾. Questo fantastico set del 2018 ti permette di costruire il treno più famoso del mondo magico, completo di locomotiva, vagone del carbone e carrozza passeggeri con tetto e pannello laterale rimovibili per facilitare il gioco all''interno. Rivivi il magico viaggio verso la scuola e preparati all''agghiacciante attacco a bordo! Compra un dolcetto dalla Strega del carrello, per poi usare l''incantesimo del Professor Lupin per scacciare la creatura oscura. Il set include la banchina con il ponte ferroviario, l''orologio, l''ingresso segreto e 6 minifigure: Harry Potter, Ron Weasley, Hermione Granger, Remus Lupin, la Strega del carrello e un Dissennatore, oltre alla figura del topo Crosta.', 69.99, 'Harry Potter', 7);

-- ==========================================
-- INSERIMENTO SET TEMA: INDIANA JONES
-- ==========================================
INSERT INTO Set_Lego (Codice_Set, Nome, Anno_Uscita, Anno_Ritiro, N_Pezzi, Descrizione, Prezzo, Tema, Quantita_Magazzino) VALUES
(7621, 'Indiana Jones e il sepolcro perduto', 2008, 2009, 277, 'Calati nelle oscure profondità del Pozzo delle Anime con questo avvincente set del 2008 tratto dal capolavoro "I Predatori dell''Arca Perduta"! Indiana Jones e Marion Ravenwood sono rimasti intrappolati nella tomba sotterranea, circondati da un''infinità di pericolosi serpenti velenosi. Aiuta Indy a trovare una via di fuga sfruttando l''ambiente circostante: usa l''iconica frusta e attiva il meccanismo per far crollare l''imponente statua del dio Anubi, sfondando così la parete del sepolcro per scappare verso la libertà! Un set storico e ricco di azione che nasconde la magnifica e dorata Arca dell''Alleanza, un altare segreto e decine di insidiosi serpenti. Contiene 3 minifigure da collezione: Indiana Jones con il suo immancabile fedora, Marion Ravenwood e un inquietante scheletro. Un vero pezzo di storia per il tuo caveau di avventuriero!', 199.99, 'Indiana Jones', 3),
(7623, 'Fuga dal tempio', 2008, 2009, 554, 'Rivivi la leggendaria sequenza d''apertura de "I Predatori dell''Arca Perduta" con questo spettacolare set del 2008! Accompagna Indiana Jones e la sua infida guida Satipo nelle profondità dell''antico tempio peruviano per recuperare il prezioso Idolo d''Oro della fertilità. Ma attenzione alle numerose trappole letali nascoste nell''oscurità: usa la frusta per oltrepassare il baratro senza fondo, schiva le lance a scatto dalla parete e lanciati in una folle corsa per sfuggire al gigantesco masso rotolante! Una volta fuori dal tempio, dovrai vedertela con l''acerrimo rivale Belloq prima di saltare a bordo dell''idrovolante di Jock per una fuga all''ultimo respiro. Un modello epico e ricchissimo di meccanismi di gioco interattivi. Il set include l''aereo e ben 4 minifigure: Indiana Jones, Satipo, René Belloq e il pilota Jock, oltre a scheletri, ragni e l''immancabile idolo.', 399.99, 'Indiana Jones', 2),
(7627, 'Il Tempio del Teschio di Cristallo', 2008, 2009, 929, 'Il culmine dell''avventura nel Regno del Teschio di Cristallo! Esplora le antiche e misteriose rovine di Akator con questo imponente e spettacolare set del 2008. Accompagna Indiana Jones e Mutt Williams nelle profondità del tempio, ma fai molta attenzione alle letali trappole: supera le scale mobili che collassano, schiva gli obelischi cadenti e difenditi dagli agguati dei feroci guerrieri indigeni. Riuscirai ad aprire l''ingresso della camera segreta per svelare l''enigma degli alieni prima della spietata Irina Spalko? Il set è ricchissimo di meccanismi di gioco e stanze nascoste, e include un veicolo cingolato da esplorazione, elementi fluorescenti e un ricco cast di personaggi. Troverai ben 10 minifigure: Indiana Jones, Mutt Williams, Irina Spalko, un soldato russo, due guerrieri Ugha, oltre a tre misteriosi scheletri di cristallo alieni e un esploratore caduto. Un modello maestoso per coronare la tua collezione!', 324.99, 'Indiana Jones', 3),
(7199, 'Il Tempio Maledetto', 2009, 2010, 652, 'Rivivi l''incredibile inseguimento sotterraneo sui carrelli da miniera, una delle scene d''azione più iconiche de "Il Tempio Maledetto"! In questo spettacolare set del 2009, Indy, Willie e Short Round devono sfuggire alle grinfie del malvagio sacerdote Mola Ram. Salta a bordo dei carrelli e sfreccia a folle velocità lungo i tortuosi binari della miniera, schivando le trappole e i pericoli che si celano nell''oscurità. Il modello è dominato dal maestoso e inquietante altare della dea Kālī, dotato di una botola segreta e di un mattoncino luminoso per far brillare le mistiche Pietre di Sankara. Riuscirai a recuperare le pietre e a fuggire prima che i nemici ti taglino la strada? Il set include 6 fantastiche minifigure: Indiana Jones, Willie Scott, Short Round, Mola Ram e due spietate guardie Thuggee, oltre alle classiche armi e all''immancabile frusta. Un vero e proprio capolavoro dinamico e ricco di azione per la tua collezione!', 589.99, 'Indiana Jones', 1),
(77015, 'Il Tempio dell’idolo d’oro', 2023, 2024, 1545, 'Celebra il capolavoro cinematografico "I Predatori dell''Arca Perduta" con questo magnifico diorama pensato per un pubblico adulto. Uscito nel 2023, questo set da esposizione altamente dettagliato ricrea fedelmente la leggendaria sequenza d''apertura del film. Sfrutta le eleganti manopole integrate nella base nera per attivare le spettacolari funzioni interattive: fai crollare le mura del tempio, usa la liana per far oscillare Indy oltre l''abisso insidioso, scatenagli alle calcagna il gigantesco masso rotolante e illumina il misterioso Idolo d''Oro grazie a un ingegnoso mattoncino luminoso! Un''esperienza di costruzione appagante, perfetta per essere esposta nel tuo caveau. Il modello include 4 iconiche minifigure: Indiana Jones, il suo inaffidabile aiutante Satipo, il rivale René Belloq e un guerriero Hovitos. Un trionfo di nostalgia e dettagli per ogni vero fan di Indy!', 136.99, 'Indiana Jones', 16);

-- ==========================================
-- INSERIMENTO SET TEMA: GHOSTBUSTERS
-- ==========================================
INSERT INTO Set_Lego (Codice_Set, Nome, Anno_Uscita, Anno_Ritiro, N_Pezzi, Descrizione, Prezzo, Tema, Quantita_Magazzino) VALUES
(75827, 'Caserma dei Vigili del Fuoco', 2016, 2018, 4634, 'Ricrea le iconiche scene degli Acchiappafantasmi con la spettacolare Caserma dei Vigili del Fuoco dei Ghostbusters! Questo monumentale set del 2016, composto da oltre 4.600 pezzi, è un vero capolavoro di dettagli strutturato su tre piani. Apri le pareti a cerniera dell''edificio per esplorare l''interno in ogni sua parte: fai scivolare i protagonisti lungo il classico palo dei pompieri per rispondere a una chiamata, cattura gli spiriti e rinchiudili nell''unità di contenimento al piano terra, oppure analizza la melma psicocinetica nel laboratorio. Questo capolavoro per veri collezionisti include ben 9 minifigure: Peter Venkman, Ray Stantz, Egon Spengler, Winston Zeddemore, Janine Melnitz, Dana Barrett, Louis Tully, il Fantasma della Biblioteca e l''Autista Zombie, oltre all''immancabile Slimer e ad altri due fantasmi trasparenti. Un pezzo da esposizione imperdibile per ogni appassionato del paranormale!', 559.99, 'Ghostbusters', 3),
(75828, 'Ecto-1 & 2', 2016, 2017, 556, 'Scendi in strada e preparati ad acchiappare i fantasmi di New York con il set Ecto-1 & 2, ispirato al film Ghostbusters del 2016! Sfreccia a bordo della nuova e fiammante Ecto-1, dotata di tetto rimovibile, porte e bagagliaio apribili, perfetti per caricare al volo gli zaini protonici e le trappole. Quando l''azione si sposta in spazi più stretti, lancia Kevin all''inseguimento a bordo della scattante moto Ecto-2. Questo divertente set è equipaggiato con misuratori PKE e tutto il necessario per dare la caccia alle entità paranormali, affrontando il temibile demone rosso volante Mayhem. Include le 5 minifigure complete del nuovo team: Abby Yates, Erin Gilbert, Jillian Holtzmann, Patty Tolan e il receptionist Kevin, oltre alla figura trasparente del mostruoso Mayhem. Un set perfetto per ricreare le scene più divertenti della pellicola!', 99.99, 'Ghostbusters', 6);

-- ==========================================
-- INSERIMENTO SET TEMA: THE SIMPSONS
-- ==========================================
INSERT INTO Set_Lego (Codice_Set, Nome, Anno_Uscita, Anno_Ritiro, N_Pezzi, Descrizione, Prezzo, Tema, Quantita_Magazzino) VALUES
(71006, 'La casa dei Simpsons', 2014, 2017, 2523, 'Benvenuti a Springfield! Costruisci ed esplora la leggendaria casa della famiglia più amata della televisione con questo straordinario set del 2014. Il tetto è facilmente rimovibile e l''intero edificio si apre a cerniera per rivelare interni incredibilmente dettagliati. Al piano terra troverai il soggiorno con l''iconico divano e la TV sintonizzata su Grattachecca e Fichetto, oltre alla cucina completamente attrezzata con tavolo da pranzo e utensili. Al piano superiore ti aspettano la camera da letto di Homer e Marge con la culla di Maggie, la disordinata stanza di Bart e la camera di Lisa. All''esterno non manca il garage, completo di banco da lavoro e della famosa auto rosa di famiglia, con tanto di ammaccatura sul paraurti! Nel giardino troverai il barbecue, le sdraio e la rampa da skate di Bart. Il set include 6 esclusive minifigure: Homer, Marge, Bart, Lisa, Maggie e l''immancabile vicino Ned Flanders.', 459.99, 'The Simpsons', 3),
(71016, 'Jet Market', 2015, 2017, 2179, 'Benvenuti al Jet Market! Fai la spesa nel minimarket più famoso di Springfield con questo incredibile e dettagliatissimo set del 2015. L''edificio si apre a cerniera e presenta un tetto rimovibile per esplorare facilmente ogni angolo del negozio gestito da Apu. L''interno è un vero paradiso di citazioni per i fan della serie animata: troverai scaffali colmi di prodotti iconici come la Buzz Cola, i cereali Krusty-O''s e la Zuppa per Uno, oltre alla mitica macchina per lo Squishee, i videogiochi arcade, le telecamere di sicurezza e un bancomat. All''esterno puoi ammirare l''orto segreto sul tetto di Apu e l''auto della polizia del Commissario Winchester, appena arrivata per sventare l''ennesima rapina. Il set include l''auto e 6 esclusive minifigure: Homer, Bart, Marge, Apu Nahasapeemapetilon, il Commissario Winchester e l''immancabile ladro Serpente.', 509.99, 'The Simpsons', 1);

-- ==========================================
-- INSERIMENTO SET TEMA: AGENTS
-- ==========================================
INSERT INTO Set_Lego (Codice_Set, Nome, Anno_Uscita, Anno_Ritiro, N_Pezzi, Descrizione, Prezzo, Tema, Quantita_Magazzino) VALUES
(8633, 'Soccorso in motoscafo', 2008, 2009, 340, 'Entra nel vivo dell''azione con la squadra speciale dei LEGO Agents in questa avvincente missione acquatica del 2008! I malvagi scagnozzi del Dr. Inferno hanno catturato l''Agente Trace e la tengono prigioniera su una piattaforma galleggiante difesa da uno squalo robotico laser. Salta al comando del potentissimo motoscafo hi-tech dell''Agente Chase, un concentrato di ingegneria spionistica dotato di missili a scatto nascosti, un computer di bordo e una moto d''acqua d''emergenza che può essere sganciata istantaneamente dal retro per un attacco a sorpresa. Evita le trappole nemiche, sconfiggi il temibile Break Jaw e porta a termine il salvataggio prima che sia troppo tardi. Il set include dettagliati meccanismi di gioco e 3 esclusive minifigure: l''Agente Chase, l''Agente Trace e Break Jaw, oltre allo squalo cibernetico. Un mix perfetto di gadget segreti e azione mozzafiato!', 99.99, 'Agents', 2),
(8634, 'Turbocar all''inseguimento', 2008, 2009, 498, 'Sfreccia a tutta velocità con l''Agente Chase in questa adrenalinica missione spionistica del 2008! Il malvagio Spy Clops ha sottratto un computer portatile contenente file top-secret e sta tentando la fuga a bordo del suo elicottero d''assalto modificato. Mettiti alla guida della leggendaria Turbocar, una supercar blu e argento che nasconde un arsenale di tecnologia difensiva hi-tech. Attiva i lancia-missili a scomparsa, schiva gli attacchi aerei e usa i gadget di bordo per neutralizzare la minaccia prima che le informazioni sensibili finiscano nelle mani del Dr. Inferno. Il set garantisce un''azione mozzafiato grazie alle funzioni interattive dei veicoli e include 3 minifigure: l''Agente Chase, il cibernetico Spy Clops e un fedele scagnozzo, oltre al laptop segreto e svariate armi da super spia. Un pezzo dinamico e ricco di fascino nostalgico!', 189.99, 'Agents', 4),
(8635, 'Centro comando mobile', 2008, 2009, 1154, 'Il quartier generale supremo dei LEGO Agents è pronto all''azione! Questo colossale set del 2008, composto da oltre 1.100 pezzi, ti permette di costruire il maestoso Centro Comando Mobile. Il grande camion hi-tech si apre completamente per rivelare una base operativa super attrezzata, dotata di schermi radar, un laboratorio di analisi, una cella di detenzione per i criminali catturati e una baia di riparazione. Affronta le forze del Dr. Inferno e proteggi i lingotti d''oro dall''assalto nemico! Il set è ricchissimo di mezzi di supporto, tra cui un jet spia a reazione, una moto d''acqua e una mini-auto sportiva nascosta nel rimorchio. Include ben 7 minifigure: gli Agenti Chase, Charge, Swift e Fuse, insieme ai malvagi Spy Clops, Gold Tooth e uno scagnozzo del Dr. Inferno. Un set monumentale, pieno di gadget tecnologici e funzioni interattive, perfetto per coronare la tua collezione di super spie!', 409.99, 'Agents', 1),
(8637, 'Volcano Base', 2008, 2008, 718, 'Entra nel covo definitivo del male con la base segreta del Dr. Inferno nascosta all''interno di un vulcano attivo! Questo spettacolare set del 2008 rappresenta il culmine della prima ondata della serie LEGO Agents ed è strutturato per lanciare l''assalto finale prima che il supercriminale attivi il suo letale cannone laser orbitale. La roccaforte è difesa da trappole insidiose, fiumi di lava, una botola segreta e una prigione sospesa nel vuoto per rinchiudere le spie catturate. Gli intrepidi agenti Chase e Trace dovranno infiltrarsi nella struttura grazie al loro elicottero d''attacco hi-tech per salvare la situazione. Ricca di meccanismi di gioco e pareti apribili, la fortezza include 6 minifigure: gli Agenti Chase e Trace, il Dr. Inferno con il suo braccio meccanico, i tirapiedi potenziati Claw-Dette e Fire-Arm, e un soldato semplice. Un modello epico e ricco di azione per coronare la tua collezione di super spie!', 414.99, 'Agents', 0),
(8970, 'Roboattacco', 2009, 2009, 414, 'Preparati a difendere la città dal gigantesco Roboattacco guidato dal malvagio Dr. Inferno in persona! In questo iconico e massiccio set del 2009, la nemesi dei LEGO Agents semina il panico a bordo di un enorme mech meccanico super articolato, dotato di un braccio artiglio frantumatore, un lancia-missili a ripetizione e una cabina di pilotaggio espellibile. Spetta all''Agente Chase e all''Agente Trace intervenire tempestivamente per fermare la minaccia prima che sia troppo tardi, sfruttando un agile elicottero di supporto e un quad hi-tech per aggirare il colosso di metallo. Il modello offre un''ottima giocabilità grazie ai suoi snodi e alle funzioni di sparo, e include 3 minifigure: l''Agente Chase, l''Agente Trace e il Dr. Inferno con la sua divisa hi-tech. Un pezzo imponente e carico di azione dinamica per la tua collezione!', 109.99, 'Agents', 3);

-- ==========================================
-- INSERIMENTO SET TEMA: STAR WARS
-- ==========================================
INSERT INTO Set_Lego (Codice_Set, Nome, Anno_Uscita, Anno_Ritiro, N_Pezzi, Descrizione, Prezzo, Tema, Quantita_Magazzino) VALUES
(7200, 'Final Duel I', 2002, 2003, 29, 'Rivivi l''epico scontro finale a bordo della seconda Morte Nera con questo storico set del 2002 tratto dal capolavoro "Il Ritorno dello Jedi"! Nonostante le dimensioni ridotte di soli 29 pezzi, questo modello riesce a catturare l''essenza della sala del trono dell''Imperatore. Il set include una piccola sezione di passerella con una ringhiera abbattibile per simulare i danni del duello e un pannello di controllo imperiale. Il vero tesoro per i collezionisti sono le due minifigure incluse: il leggendario Darth Vader, con la sua classica spada laser rossa, e una Guardia Reale Imperiale.', 78.99, 'Star Wars', 3),
(4476, 'Jabba''s Prize', 2003, 2003, 40, 'Un piccolo ma iconico pezzo di storia di Star Wars direttamente dal palazzo di Jabba the Hutt! Rilasciato nel 2003, questo set ricrea il drammatico momento in cui Han Solo viene tenuto prigioniero nella carbonite dopo gli eventi di "L''Impero Colpisce Ancora". Nonostante i soli 39 pezzi, il set include elementi fantastici per i collezionisti: il blocco di carbonite in cui è intrappolato il contrabbandiere, una sezione di muro con pannello di controllo e ben due minifigure leggendarie, ovvero il celebre cacciatore di taglie Boba Fett e una guardia Gamorreana armata d''ascia. Un pezzo vintage immancabile per ricreare l'atmosfera desertica di Tatooine nel tuo caveau!', 162.99, 'Star Wars', 2),
(4480, 'Jabba''s Palace', 2003, 2004, 231, 'Infiltrati nel covo del più temuto signore del crimine di Tatooine con la primissima e storica versione del Palazzo di Jabba the Hutt del 2003! Questo mitico set da 234 pezzi cattura perfettamente il fascino rétro dei primi anni di LEGO Star Wars. La struttura presenta l''iconica torre del palazzo, un portone d''ingresso scorrevole e la sala del trono dotata di una botola funzionante per far cadere i prigionieri nella fossa sottostante. Il set include personaggi d''eccezione tra cui la figura vintage di Jabba, Luke Skywalker in versione Cavaliere Jedi, la Principessa Leia travestita da Boushh, il droide EV-9D9 e un rarissimo monaco B''omarr con le sue zampe da ragno. Un vero pilastro da collezione!', 279.99, 'Star Wars', 1),
(7251, 'Darth Vader Transformation', 2005, 2005, 53, 'Assisti alla drammatica nascita del Signore Oscuro dei Sith con questo memorabile set del 2005 ispirato a "La Vendetta dei Sith"! Rivivi il momento clou in cui Anakin Skywalker completa la sua tragica transizione diventando Darth Vader. Grazie a un ingegnoso meccanismo centrale, la tavola medica può essere ruotata e inclinata per trasformare fisicamente la minifigure ferita di Anakin nel temibile Vader con la sua iconica armatura nera e l''elmo. Il set include tre minifigure fondamentali per la saga: l''Imperatore Palpatine, Anakin Skywalker ferito e Darth Vader con la sua spada laser rossa, oltre a un braccio robotico medico. Un piccolo set dal valore storico immenso!', 79.99, 'Star Wars', 4),
(10144, 'Sandcrawler', 2005, 2008, 1669, 'Attraversa le desolate dune di Tatooine a bordo del maestoso e gigantesco Sandcrawler dei Jawa! Uscito nel 2005, questo imponente modello da ben 1.768 pezzi è stato per anni uno dei set più desiderati dai collezionisti di tutto il mondo. La colossale fortezza cingolata marrone è interamente apribile grazie a pannelli laterali e posteriori a cerniera, rivelando un interno ricchissimo di officine, nastri trasportatori e una gru magnetica funzionante per sollevare e caricare i droidi catturati. Il set include ben 11 minifigure e droidi tra cui lo zio Owen Lars, tre Jawa, C-3PO, R2-D2 e svariati droidi astromeccanici rari. Un capolavoro di ingegneria LEGO d''altri tempi per il tuo caveau!', 469.99, 'Star Wars', 1),
(10188, 'Death Star', 2008, 2010, 3803, 'Prendi il controllo dell''arma suprema dell''Impero con la leggendaria Morte Nera del 2008! Questo colossale set da ben 3.803 pezzi è un assoluto capolavoro di giocabilità ed esposizione, strutturato su più livelli aperti che ricreano le scene più iconiche della trilogia originale. Esplora la sala del superlaser, la cella di detenzione di Leia, il compattatore di rifiuti funzionante, la sala del trono dell''Imperatore e l''hangar con un TIE Advanced in miniatura. Con una sbalorditiva selezione di 24 minifigure e droidi (tra cui Luke, Han, Darth Vader, Obi-Wan e l''Imperatore), potrai rivivere ogni momento memorabile della saga. Il pezzo definitivo per eccellenza per coronare la tua collezione!', 684.99, 'Star Wars', 2),
(9516, 'Jabba''s Palace', 2012, 2013, 717, 'Ritorna nel palazzo del crimine con la spettacolare e dettagliatissima versione del 2012 del Palazzo di Jabba! Composto da 717 pezzi, questo modello offre un''esperienza di costruzione superba con la sua torre rimovibile e il tetto a cupola della sala del trono. Il trono di Jabba può scorrere in avanti per rivelare un vano segreto e azionare la letale botola che conduce alla fossa del Rancor. Il vero punto di forza è l''incredibile cast di 9 minifigure: il maestoso Jabba the Hutt con stampi moderni, Salacious Crumb, Bib Fortuna, una guardia Gamorreana, la danzatrice Oola, Han Solo, Chewbacca e Leia in abiti Boushh. Un diorama mozzafiato, ricco di trappole e dettagli fantastici!', 324.99, 'Star Wars', 5);
